version: 2

registries:
  skycd:
    type: nuget-feed
    url: https://nuget.pkg.github.com/SkyCD/index.json
    username: SkyCD
    password: ${{secrets.PACKAGES_PAT}}

updates:
  - package-ecosystem: nuget
    directory: "/"
    registries:
      - skycd
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "Europe/Vilnius"
    open-pull-requests-limit: 8
    labels:
      - dependencies
      - type:platform
    commit-message:
      prefix: "chore(deps)"
    groups:
      dotnet-core:
        applies-to: version-updates
        patterns:
          - "Microsoft.*"
          - "System.*"
      test-stack:
        applies-to: version-updates
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet*"
      security-nuget:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: "Europe/Vilnius"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - type:platform
    commit-message:
      prefix: "chore(ci-deps)"
    groups:
      actions-routine:
        applies-to: version-updates
        patterns:
          - "*"
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"
