// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyCD.Infrastructure.Persistence;

#nullable disable

namespace SkyCD.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SkyCdDbContext))]
    partial class SkyCdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SkyCD.Domain.Catalogs.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catalogs", (string)null);
                });

            modelBuilder.Entity("SkyCD.Domain.Catalogs.CatalogNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("CatalogId", "Kind");

                    b.HasIndex("CatalogId", "ParentId");

                    b.HasIndex("CatalogId", "ParentId", "Name", "Kind")
                        .IsUnique();

                    b.ToTable("CatalogNodes", (string)null);
                });

            modelBuilder.Entity("SkyCD.Domain.Catalogs.CatalogTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "Name");

                    b.ToTable("CatalogTags", (string)null);
                });

            modelBuilder.Entity("SkyCD.Domain.Catalogs.CatalogNode", b =>
                {
                    b.HasOne("SkyCD.Domain.Catalogs.Catalog", "Catalog")
                        .WithMany("Nodes")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyCD.Domain.Catalogs.CatalogNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Catalog");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkyCD.Domain.Catalogs.CatalogTag", b =>
                {
                    b.HasOne("SkyCD.Domain.Catalogs.Catalog", "Catalog")
                        .WithMany("Tags")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SkyCD.Domain.Catalogs.Catalog", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SkyCD.Domain.Catalogs.CatalogNode", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
